language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
before_script:
  - printf "\n" | pecl install imagick
  - composer self-update
  - composer install
script:
  - vendor/bin/phpunit
after_success:
  - travis_retry php vendor/bin/coveralls -v